# MCU name
MCU = atmega32u4
# BOOTLOADER = caterina
BOOTLOADER = caterina
F_CPU = 16000000
# ARCH = AVR8
# F_USB = $(F_CPU)

# Interrupt driven control endpoint task(+60)
# OPT_DEFS += -DINTERRUPT_CONTROL_ENDPOINT

# Boot Section Size in *bytes*
# OPT_DEFS += -DBOOTLOADER_SIZE=4096

BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = yes
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = yes
ENCODER_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
# TAP_DANCE_ENABLE = yes
